# Use container on EC2, other options available (venvs)[https://docs.travis-ci.com/user/reference/overview/]
sudo: false
dist: trusty

language: python
python:
  - "2.7"
  - "3.6"
  - "3.7-dev"

notifications:
  email: false

install:
  - make dev-dependencies  # Install python development dependencies
  - make package

script:
  - make test  # pytest
  - make check-linting-pylint  # pylint fatf/
  - make check-linting-flake8  # flake8 fatf/
  - make code-coverage  # pytest --cov=./ --cov-report xml

after_success:
  - codecov -t $CODECOV_TOKEN
