# Use container on EC2, other options available (venvs)[https://docs.travis-ci.com/user/reference/overview/]
sudo: false
dist: trusty

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

notifications:
  email: false

install:
  - make dependencies-dev  # Install python development dependencies
  - make install

script:
  - make linting-pylint  # pylint fatf/
  - make linting-flake8  # flake8 fatf/
  - make test  # pytest
  - make code-coverage  # pytest --cov=./ --cov-report xml
  - make doc-test  # pytest --doctest-glob='*.rst'

after_success:
  - make deploy-code-coverage
